### ISSUE TITLE
Cookie rejected

### ISSUE THREAD

**Issue by llcool** [lhall-adexos/xdebug-ext#2]
Cookie “XDEBUG_SESSION” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

Firefox 76.0.1 needs samesite set.

**Comment by lhall-amphibee** [comment]
Thanks for the heads up, I'll look into it
